CREATE TABLE [dbo].[Rental]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [CarId] UNIQUEIDENTIFIER NOT NULL, 
    [NumberOfDays] SMALLINT NOT NULL, 
    [RentalDateTime] DATETIME NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Rental_Cars] FOREIGN KEY ([CarId]) REFERENCES [Cars]([Id]), 
    CONSTRAINT [FK_Rental_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
